spring.application.name=job-tracker

# DB 연결 정보
spring.datasource.url=jdbc:postgresql://localhost:5432/job_tracker
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# JPA 설정
#update는 테이블을 자동 생성. 실제 배포 시에는 validate로 바꾼다.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#JWT 비밀키 추가
jwt.secret=${JWT_SECRET:temporary-dev-secret-key-change-this-later-1234567890}
jwt.expiration=3600000
